Name:           ros-melodic-pyros-utils
Version:        0.1.4
Release:        1%{?dist}
Summary:        ROS pyros_utils package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-rosgraph >= 1.11.19
Requires:       ros-melodic-roslaunch >= 1.11.19
Requires:       ros-melodic-rospy >= 1.11.19
Requires:       ros-melodic-rostest >= 1.11.19
BuildRequires:  ros-melodic-catkin >= 0.6.18
BuildRequires:  ros-melodic-catkin-pip >= 0.2.0
BuildRequires:  ros-melodic-pyros-test >= 0.0.3
BuildRequires:  ros-melodic-rosgraph >= 1.11.19
BuildRequires:  ros-melodic-roslaunch >= 1.11.19
BuildRequires:  ros-melodic-roslint >= 0.10.0
BuildRequires:  ros-melodic-rosnode >= 1.11.19
BuildRequires:  ros-melodic-rospy >= 1.11.19
BuildRequires:  ros-melodic-rostest >= 1.11.19
BuildRequires:  ros-melodic-rosunit >= 1.11.12

%description
Miscellaneous tools for pyROS

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Jun 18 2019 AlexV <asmodehn@gmail.com> - 0.1.4-1
- Autogenerated by Bloom

